// Compiles the partner-owned files into a typed module the app imports.
//
//   content/tree-copy.md   -> every word a visitor reads
//   public/tree/*.png      -> which art files actually exist
//
// Runs on predev and prebuild. This exists so the other half of the team can
// change copy or drop in artwork and have it take effect on the next deploy,
// with no code change and no coordination. Importing markdown directly or
// reading the filesystem at request time both have Turbopack and Vercel
// tracing footguns that are not worth discovering later.
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { resolve } from "node:path";

/** `## Heading` followed by prose, until the next heading. */
function sections(md: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const block of md.split(/^## /m).slice(1)) {
    const nl = block.indexOf("\n");
    const name = block.slice(0, nl).trim().toLowerCase();
    const body = block
      .slice(nl + 1)
      .split("\n")
      .filter((l) => !l.trim().startsWith(">") && l.trim() !== "---")
      .join("\n")
      .trim();
    out.set(name, body);
  }
  return out;
}

/** Drop the explanatory paragraph a partner may leave above the actual text. */
function lastParagraph(body: string): string {
  const paras = body.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);
  return paras.at(-1) ?? "";
}

function lines(body: string): string[] {
  const paras = body.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);
  const last = paras.at(-1) ?? "";
  return last.split("\n").map((l) => l.trim()).filter(Boolean);
}

const md = readFileSync(resolve("content/tree-copy.md"), "utf8");
const s = sections(md);

const pick = (heading: string, fallback: string) => {
  const body = s.get(heading.toLowerCase());
  const text = body ? lastParagraph(body) : "";
  return text || fallback;
};

const copy = {
  composerPlaceholder: pick("Composer placeholder", "Leave something on the tree"),
  composerButton: pick("Composer button", "Post"),
  posting: pick("Posting", "Growing the tree…"),
  milestoneHeading: pick("Milestone heading", "Milestone"),
  milestoneMessage: pick(
    "Milestone message",
    "He has climbed this far because {count} of you left something behind.",
  ),
  milestoneButton: pick("Milestone button", "Keep climbing"),
  emptyTree: pick("Empty tree", "Nobody has left anything yet. He is waiting at the bottom."),
  phaseNames: (() => {
    const body = s.get("phase names");
    const got = body ? lines(body) : [];
    return got.length === 4 ? got : ["Morning", "Long afternoon", "Dusk", "Night"];
  })(),
  seedPosts: (() => {
    const body = s.get("seed posts");
    const got = body ? lines(body) : [];
    return got.length > 0 ? got : ["made it through today"];
  })(),
};

// Which artwork has actually landed. Missing files fall back to the shapes
// drawn in code, so a half-delivered set never renders as broken images.
const dir = resolve("public/tree");
const present = existsSync(dir)
  ? new Set(readdirSync(dir).filter((f) => f.toLowerCase().endsWith(".png")))
  : new Set<string>();

const art = {
  climber: [0, 1, 2, 3].map((i) => present.has(`climber-${i}.png`)),
  leaf: [0, 1, 2].map((i) => present.has(`leaf-${i}.png`)),
  sky: [0, 1, 2, 3].map((i) => present.has(`sky-${i}.png`)),
};

writeFileSync(
  resolve("lib/tree/content.generated.ts"),
  `// GENERATED BY scripts/build-content.ts — DO NOT EDIT.
// Source: content/tree-copy.md and public/tree/*.png
export const COPY = ${JSON.stringify(copy, null, 2)} as const;

export const ART = ${JSON.stringify(art, null, 2)} as const;
`,
  "utf8",
);

const have = (a: boolean[]) => a.filter(Boolean).length;
console.log(
  `content.generated.ts written — art: ${have(art.climber)}/4 climbers, ` +
    `${have(art.leaf)}/3 leaves, ${have(art.sky)}/4 skies`,
);
