import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const source = readFileSync(resolve("WORLD.md"), "utf8");

// Escape only what breaks a template literal.
const escaped = source.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

writeFileSync(
  resolve("lib/ai/world.generated.ts"),
  `// GENERATED BY scripts/build-world.ts FROM WORLD.md — DO NOT EDIT.\nexport const WORLD = \`${escaped}\`;\n`,
  "utf8",
);

console.log(`world.generated.ts written (${source.length} chars)`);
